In [327]:
import re
import random
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.feature_extraction.text import CountVectorizer
import nltk


## Problem 1

In [276]:
x = np.random.rand(5, 4)
x

array([[0.60492051, 0.01263023, 0.69282518, 0.15366388],
       [0.62932371, 0.50132336, 0.32470633, 0.8347004 ],
       [0.67739608, 0.61959801, 0.26212914, 0.38898714],
       [0.45911014, 0.47214606, 0.05804298, 0.63545579],
       [0.61831964, 0.92400153, 0.65157502, 0.46330121]])

00 01 02 03 
l0       13 
20       23
30       33
40 41 42 43 

In [277]:
for i in range(x.shape[1]-1, -1, -1):
    print(x[x.shape[1]-i-1][i])

0.1536638849897699
0.3247063288249429
0.6195980084904766
0.4591101373131192


In [278]:
for i in x:
    print(i.max())

0.6928251781022459
0.8347004028436625
0.677396083434863
0.6354557949955619
0.9240015307530911


In [279]:
mean = x.mean()
x_ = x.flatten()
new_array = [i for i in x_ if i<=mean]
new_array

[0.012630225308793541,
 0.1536638849897699,
 0.3247063288249429,
 0.2621291403481769,
 0.38898714406459145,
 0.4591101373131192,
 0.47214605969695256,
 0.05804298055795809,
 0.4633012095209267]

In [280]:
def numpy_boundary_traversal(matrix):
    size = matrix.shape # 5, 4
    for i in range(size[0]+1):
        for j in range(size[1]):
            if i==0:
                print(matrix[i][j])                
            if size[0]-1>i>0:
                print(matrix[i][size[1]-1])
                break
            if i==size[0]-1:
                print(matrix[i][size[1]-j-1])
            if i==size[0] and j<size[1]-1:
                print(matrix[i-2-j][0])
                   
            
            
numpy_boundary_traversal(x)        

0.6049205050763621
0.012630225308793541
0.6928251781022459
0.1536638849897699
0.8347004028436625
0.38898714406459145
0.6354557949955619
0.4633012095209267
0.6515750221033428
0.9240015307530911
0.6183196405542529
0.4591101373131192
0.677396083434863
0.6293237123377735


## Problem 2

In [281]:
array = np.random.uniform(0, 10, 20)
array

array([3.10021079, 3.00960338, 4.2580445 , 0.67112156, 3.00676017,
       9.63824728, 1.76927274, 8.25115413, 8.14809175, 4.62169995,
       5.65964059, 5.4759456 , 4.09989923, 0.87896327, 4.46457967,
       8.40132618, 7.89127596, 6.87598495, 3.94705509, 4.38478338])

In [282]:
rounded_array = np.round(array, 2)
rounded_array

array([3.1 , 3.01, 4.26, 0.67, 3.01, 9.64, 1.77, 8.25, 8.15, 4.62, 5.66,
       5.48, 4.1 , 0.88, 4.46, 8.4 , 7.89, 6.88, 3.95, 4.38])

In [283]:
print(f"mean={rounded_array.mean()} \n max={rounded_array.max()} \n min={rounded_array.min()}")

mean=4.928 
 max=9.64 
 min=0.67


In [284]:
new_array = [f**2 if f<5 else f for f in rounded_array]
new_array

[9.610000000000001,
 9.060099999999998,
 18.147599999999997,
 0.4489000000000001,
 9.060099999999998,
 9.64,
 3.1329000000000002,
 8.25,
 8.15,
 21.3444,
 5.66,
 5.48,
 16.81,
 0.7744,
 19.8916,
 8.4,
 7.89,
 6.88,
 15.602500000000001,
 19.1844]

In [285]:
def numpy_alternate_sort(array):
    list= []
    while np.size(array)>0:
        min = array.min()
        max = array.max()
        list.append(min)
        list.append(max)
        array = array[array!=min]
        array = array[array!=max]
    return np.array(list)

numpy_alternate_sort(rounded_array)

array([0.67, 9.64, 0.88, 8.4 , 1.77, 8.25, 3.01, 8.15, 3.1 , 7.89, 3.95,
       6.88, 4.1 , 5.66, 4.26, 5.48, 4.38, 4.62, 4.46, 4.46])

In [286]:
rounded_array

array([3.1 , 3.01, 4.26, 0.67, 3.01, 9.64, 1.77, 8.25, 8.15, 4.62, 5.66,
       5.48, 4.1 , 0.88, 4.46, 8.4 , 7.89, 6.88, 3.95, 4.38])

## Problem 3

In [287]:
df = pd.DataFrame(columns=["Name", "Subject", "Score", "Grade"])

In [288]:
df["Name"] = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
df['Subject'] = "Math"
df['Score'] = np.array([random.randint(50, 100) for _ in range(10)])

In [289]:
def grading(num):
    if num<60: return "F"
    elif num<70: return "D"
    elif num<80: return "C"
    elif num<90: return "B"
    else: return "A"

df["Grade"] = [grading(i) for i in df["Score"]]

In [290]:
# since I 've chosen only one subject
mean = np.mean(df[df["Subject"]=="Math"]["Score"])
mean

76.2

In [291]:
def pandas_filter_pass(df):
    return df[df["Score"]>=80]

df1 = pandas_filter_pass(df)
df1

Name Subject  Score Grade
0     1    Math     81     B
3     4    Math     83     B
4     5    Math     83     B
6     2    Math     90     A
8     4    Math     95     A

## Problem 4


In [292]:
data  = pd.read_csv("IMDB Dataset.csv")
data_= data.sample(100)

In [293]:
data_.head(5)

review sentiment
12255  This movie has got to be the worse movie i hav...  negative
38993  I read about this movie in a magazine and I wa...  negative
27190  So there's an old security guard and a guy who...  negative
17255  The film attempts to be a mockumentary--shot i...  negative
1372   Walter Matthau and George Burns just work so w...  positive

In [302]:
encode = LabelEncoder()
Y = encode.fit_transform(data_['sentiment'])
vect = CountVectorizer(max_features=500, stop_words="english")
X = vect.fit_transform(data_['review'])


In [303]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=69)

In [304]:
nb_model = MultinomialNB()
nb_model.fit(x_train, y_train)
y_pred = nb_model.predict(x_test)


In [305]:
acc = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [306]:
print(f"accuracy:{acc}\nprecision:{precision}\nrecall:{recall}\nf1_score:{f1}")

accuracy:0.75
precision:0.8333333333333334
recall:0.5555555555555556
f1_score:0.6666666666666667


In [ ]:
model1 = MultinomialNB()
encoder = LabelEncoder()
vectorizer = CountVectorizer(max_features=500, stop_words='english')
model1.fit(vectorizer.fit_transform(data['review']), encoder.fit_transform(data['sentiment']))

def predict_review_sentiment(model, vectorizer, review):
    txt_vect = vectorizer.transform(review)
    return model.predict(txt_vect)    

In [ ]:
rev = "I watched Housefull 5, and it’s pure chaos—loud jokes, random twists, and over-the-top madness. Akshay Kumar saves it with his comic timing, and Nana Patekar’s entry is the highlight. It’s fun if you like silly, brain-off comedies, but honestly, it left me more tired than entertained"
pred = predict_review_sentiment(model1, vectorizer, [rev])
pred 

array([0])

## Problem 5


In [314]:
feedback_data = pd.read_csv("amazon_alexa.tsv", sep='\t')

In [331]:
data1 = feedback_data[['feedback', 'verified_reviews']]
data1 = data1.dropna()

In [332]:
tfidf = TfidfVectorizer(stop_words='english', max_features=300, lowercase=True)
text_data = tfidf.fit_transform(data1['verified_reviews'])
x_tr, x_ts, y_tr, y_ts = train_test_split(text_data, data1['feedback'], test_size=.25, random_state=6)

classifier = LogisticRegression()
classifier.fit(x_tr, y_tr)
y_pred1=classifier.predict(x_ts)

In [333]:
acc = accuracy_score(y_ts, y_pred1)
precision = precision_score(y_ts, y_pred1)
recall = recall_score(y_ts, y_pred1)
f1 = f1_score(y_ts, y_pred1)
print(f"accuracy:{acc}\nprecision:{precision}\nrecall:{recall}\nf1_score:{f1}")

accuracy:0.9098984771573604
precision:0.9097839898348158
recall:1.0
f1_score:0.9527611443779108


In [338]:
def text_preprocess_vectorize(texts, vectorizer):
    '''
    texts: list of text samples
    '''
    vect = vectorizer.transform(texts)
    return vect.toarray()

In [340]:
text_preprocess_vectorize(['I love alexa, it is a great product', 'worst product I coulf have brought'], tfidf)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.5002581 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  